title: Steffen Eikenberry
logo: /images/portfolio_pic2.jpg
description: "Data Science Portfolio Assistant Clinical Professor, Data Science"
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
